### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by inescoelho** [inescoelho/inescoelho.github.io#1]
- [ ] Add projetc page
- [ ] Add talks page
- [ ] Add publications page
- [ ] Add organizations
- [ ] Add organizations page
